spring.application.name=product-service
server.port=8081

# R2DBC H2 (in-memory)
spring.r2dbc.url=r2dbc:h2:mem:///productdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.username=sa
spring.r2dbc.password=

# ????? ??????? ??????? ????? schema.sql
spring.sql.init.mode=always