spring.application.name=product-service
server.port=8081


spring.r2dbc.url=r2dbc:h2:mem:///productdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.username=sa
spring.r2dbc.password=

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.r2dbc.initialization-mode=always
logging.level.org.springframework.web.reactive.function.client=DEBUG
logging.level.reactor.netty.http.client=DEBUG