DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (
                         ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         NAME VARCHAR(255),
                         PRICE DOUBLE,
                         ADDRESS VARCHAR(255)
);