DROP TABLE IF EXISTS "PRODUCT";
DROP TABLE IF EXISTS product;

CREATE TABLE "PRODUCT" (
                           "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           "name" VARCHAR(255),
                           "price" BIGINT,
                           "address" VARCHAR(255)
);